---
title: Mariah Lattas
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mariah@mariahlattas.com
description: Journalist, podcaster, feminist.
baseurl: ''
url: https://mariah.jden.me
icon: "/assets/images/icon-512.png"
twitter_username: patdryburgh
github_username: patdryburgh
markdown: kramdown
plugins:
- jekyll-paginate-v2
paginate: 5
paginate_path: "/page/:num/"
hide_credits: true
